<Project>
  <PropertyGroup>
    <IsTestProject Condition="'$(IsTestProject)' == ''">true</IsTestProject>
  </PropertyGroup>
  <PropertyGroup Condition="$(IsTestProject)">
    <OutputType>Exe</OutputType>
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --report-trx</TestingPlatformCommandLineArguments>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Prefer32Bit>false</Prefer32Bit>
    <RuntimeIdentifier Condition="$(Is64BitOS)">win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="appsettings*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="$(IsTestProject)">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 8.0))">
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="Xunit.v3.ParallelizationAttribute" Condition="$(IsTestProject)">
      <_Parameter1>Mode = Xunit.Sdk.ParallelMode.All</_Parameter1>
      <_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>
    </AssemblyAttribute>
  </ItemGroup>
</Project>